services:
  website:
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION:-8.3}
    profiles: [website]
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG="client_host=host.docker.internal"
    working_dir: "/app" 
    command: ["php", "-S", "0.0.0.0:80", "-t", "/app/web"]
    volumes:
      - .:/app
    ports:
      - "8888:80"
    depends_on:
      - install
  install:
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION:-8.3}      
    profiles: [website]
    working_dir: "/app" 
    command: ["composer", "install"]
    volumes:
      - .:/app
  bash:
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION:-8.3}      
    profiles: [website]
    working_dir: "/app"
    command: ["bash"]
    volumes:
      - .:/app
